In [7]:
import pandas as pd
computers_data = pd.read_csv("C:/Users/91918/OneDrive/Desktop/SUDHEERA/DataScience with Gen Ai/Course-8/Project/DS1_C8_Computers_Data_Project.csv")
computers_data

,index,price,speed,hd,ram,screen,cd,multi,premium,ads_2022,ads_2023,trend
0,1,1499,25,80,4,14,no,no,yes,94,94,1
1,2,1795,33,85,2,14,no,no,yes,94,94,1
2,3,1595,25,170,4,15,no,no,yes,94,94,1
3,4,1849,25,170,8,14,no,no,no,94,94,1
4,5,3295,33,340,16,14,no,no,yes,94,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6254,6255,1690,100,528,8,15,no,no,yes,39,70,35
6255,6256,2223,66,850,16,15,yes,yes,yes,39,70,35
6256,6257,2654,100,1200,24,15,yes,no,yes,39,70,35
6257,6258,2195,100,850,16,15,yes,no,yes,39,70,35
6258,6259,2490,100,850,16,17,yes,no,yes,39,70,35

In [9]:
#task1:
import scipy.stats as stats
import numpy as np

# Given data
sample_size = 40
population_mean = 221.3  # Mean advertising budget in 2022
population_std = 74.83   # Standard deviation of the population
significance_level = 0.05

# Sample mean
sample_mean = 230

# Calculate the z-statistic
z_statistic = (sample_mean - population_mean) / (population_std / np.sqrt(sample_size))

# Calculate the critical value for a one-tailed test (right-tailed)
critical_value = stats.norm.ppf(1 - significance_level)

# Output the results
print(f"Z-statistic: {z_statistic}")
print(f"Critical Value: {critical_value}")

# Decision Rule
if z_statistic > critical_value:
    print("Reject the null hypothesis: The average advertising budget in 2023 is higher than in 2022.")
else:
    print("Fail to reject the null hypothesis: The average advertising budget in 2023 is not higher than in 2022.")

Z-statistic: 0.7353151314570324
Critical Value: 1.6448536269514722
Fail to reject the null hypothesis: The average advertising budget in 2023 is not higher than in 2022.

In [13]:
#Task2:
import pandas as pd
import scipy.stats as stats
# Separate the two groups based on whether the computer has a CD player or not
prices_with_cd = computers_data[computers_data['cd'] == 'yes']['price']
prices_without_cd = computers_data[computers_data['cd'] == 'no']['price']

# Perform an independent two-sample t-test (Welch's t-test assuming unequal variances)
t_stat, p_value = stats.ttest_ind(prices_with_cd, prices_without_cd, equal_var=False)

# Output the results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Decision rule based on p-value
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in the average prices.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in the average prices.")

T-statistic: 16.07486310306849
P-value: 5.242465665078034e-57
Reject the null hypothesis: There is a significant difference in the average prices.

In [ ]:
#Task3.a:
import pandas as pd
import scipy.stats as stats
import numpy as np
# Filter premium computers
premium_computers = computers_data[computers_data['premium'] == 'yes']

# Randomly select 25 premium computers
sample_premium = premium_computers['price'].sample(n=25, random_state=1)

# Define the population mean
population_mean = 2200

# Calculate the sample mean and sample standard deviation
sample_mean = np.mean(sample_premium)
sample_std = np.std(sample_premium, ddof=1)  # ddof=1 for sample standard deviation

# Perform the one-sample t-test
t_stat, p_value = stats.ttest_1samp(sample_premium, population_mean)

# Output the results
print(f"Sample Mean: {sample_mean}")
print(f"Sample Standard Deviation: {sample_std}")
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Decision rule based on p-value
if p_value < 0.05:
    print("Reject the null hypothesis: The mean price of premium computers differs significantly from $2200.")
else:
    print("Fail to reject the null hypothesis: The mean price of premium computers does not differ significantly from $2200.")

In [6]:
#task3.b:
import pandas as pd
import scipy.stats as stats

# Assuming df is your DataFrame containing the dataset
# Filter the data to separate prices of premium and non-premium computers
premium_computers = computers_data[computers_data['premium'] == 'yes']['price']
non_premium_computers = computers_data[computers_data['premium'] == 'no']['price']

# Perform a two-sample t-test assuming equal variances
t_stat, p_value = stats.ttest_ind(premium_computers, non_premium_computers, equal_var=True)

# Output the results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Decision rule based on p-value
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in the mean prices of premium and non-premium computers.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in the mean prices of premium and non-premium computers.")

T-statistic: -6.404063996063658
P-value: 1.622883063853707e-10
Reject the null hypothesis: There is a significant difference in the mean prices of premium and non-premium computers.